//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextTagger {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Model {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Model() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TextTagger.Model", typeof(Model).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOUN,inan,femn,plur,gent VERB,perf,intr,plur,past,indc 1 PRTF,perf,intr,past,actv,plur,gent ADJF,Qual,plur,gent 1 VERB,perf,intr,masc,sing,past,indc NOUN,inan,femn,sing,ablt 3 NOUN,anim,masc,plur,nomn NOUN,inan,masc,sing,gent 7 NONE NOUN,anim,masc,plur,accs 2 NPRO,1per,plur,gent PREP 1 NONE NOUN,inan,masc,Geox,sing,nomn 1 NOUN,inan,femn,sing,accs UNKN 5 NOUN,inan,femn,sing,accs NOUN,inan,masc,Orgn,sing,gent 1 NPRO,neut,sing,loct NOUN,anim,masc,plur,datv 1 NPRO,masc,3per,sing,nomn PREP 3 ADJF,Supr,Qual,femn, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mmodel {
            get {
                return ResourceManager.GetString("mmodel", resourceCulture);
            }
        }
    }
}
